# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93650b1c9926855e1d8d87e0a47029b53d5478ea30d353d52bd5ce570a3b08b8f56f48efb634b0ce4cd6a0fa5ea8e9737f8bed6e5a12a77959dbb189d823fb2c

test:
  secret_key_base: e53dbae5b3a33f868653c24a68df4929cb2660d607fc20839d064c723f0cadb29cca71c28c37888bd184d647e2ba71be15659e8231e164e2c8bfeec7005a26cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
